#!/bin/bash

#set -e

if [ "$1" = "configure" ] ; then
	echo "mod package: configureing"

	sites=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`

    ln -s /usr/share/yats/site-packages/yats $sites 2>/dev/null
    ln -s /usr/share/yats/site-packages/simple_sso $sites 2>/dev/null
    ln -s /usr/share/yats/site-packages/bootstrap_toolkit $sites 2>/dev/null
    ln -s /usr/share/yats/site-packages/rpc4django $sites 2>/dev/null
    ln -s /usr/share/yats/site-packages/graph $sites 2>/dev/null
		ln -s /usr/share/yats/site-packages/pyxmpp2 $sites 2>/dev/null
		ln -s /usr/share/yats/site-packages/djradicale $sites 2>/dev/null
		ln -s /usr/share/yats/site-packages/radicale $sites 2>/dev/null		

     ret=`grep -ir "TCPSocket" /etc/clamav/clamd.conf`
     if [ "" = "$ret" ]; then
		echo "TCPSocket 3310" >> /etc/clamav/clamd.conf
     fi

     ret=`grep -ir "TCPAddr" /etc/clamav/clamd.conf`
     if [ "" = "$ret" ]; then
		echo "TCPAddr 127.0.0.1" >> /etc/clamav/clamd.conf
     fi
fi

exit 0
