#!/bin/bash

#set -e

if [ "$1" = "upgrade" ] ; then
    echo "mod package: upgrading"
    rm -r /usr/share/yats/site-packages/django 2>/dev/null

    rm -r /usr/share/yats/site-packages/yats 2>/dev/null
    rm -r /usr/share/yats/site-packages/south 2>/dev/null
    rm -r /usr/share/yats/site-packages/bootstrap_toolkit 2>/dev/null
    rm -r /usr/share/yats/site-packages/rpc4django 2>/dev/null
    rm -r /usr/share/yats/site-packages/graph 2>/dev/null
    rm -r /usr/share/yats/site-packages/simple_sso 2>/dev/null
    rm -r /usr/share/yats/site-packages/pyxmpp2 2>/dev/null
    rm -r /usr/share/yats/site-packages/djradicale 2>/dev/null
    rm -r /usr/share/yats/site-packages/radicale 2>/dev/null

fi

exit 0
