# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yats', '0002_auto_20180717_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('tickets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yats.tickets')),
                ('version', models.CharField(max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('reproduction', models.TextField(null=True)),
                ('billing_needed', models.NullBooleanField(default=True)),
                ('billing_done', models.NullBooleanField(default=None)),
                ('billing_reason', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('fixed_in_version', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('yats.tickets',),
        ),
        migrations.CreateModel(
            name='ticket_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ticket_component'),
        ),
    ]
