# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_component',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket_component',
            name='u_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
