# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180821_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_component',
            options={'ordering': ['name'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterField(
            model_name='test',
            name='billing_done',
            field=models.NullBooleanField(default=None, verbose_name='billing done'),
        ),
        migrations.AlterField(
            model_name='test',
            name='billing_estimated_time',
            field=models.FloatField(blank=True, null=True, verbose_name='billing estimated time'),
        ),
        migrations.AlterField(
            model_name='test',
            name='billing_needed',
            field=models.NullBooleanField(default=True, verbose_name='billing needed'),
        ),
        migrations.AlterField(
            model_name='test',
            name='billing_reason',
            field=models.TextField(blank=True, null=True, verbose_name='billing reason'),
        ),
        migrations.AlterField(
            model_name='test',
            name='billing_time_taken',
            field=models.FloatField(blank=True, null=True, verbose_name='billing tike taken'),
        ),
        migrations.AlterField(
            model_name='test',
            name='billing_type',
            field=models.CharField(blank=True, choices=[(b'service', b'service'), (b'development', b'development')], max_length=255, null=True, verbose_name='billing type'),
        ),
        migrations.AlterField(
            model_name='test',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ticket_component', verbose_name='component'),
        ),
        migrations.AlterField(
            model_name='test',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='test',
            name='fixed_in_version',
            field=models.CharField(blank=True, max_length=255, verbose_name='fixed in version'),
        ),
        migrations.AlterField(
            model_name='test',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='test',
            name='reproduction',
            field=models.TextField(null=True, verbose_name='reproduction'),
        ),
        migrations.AlterField(
            model_name='test',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='solution'),
        ),
        migrations.AlterField(
            model_name='test',
            name='version',
            field=models.CharField(max_length=255, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='ticket_component',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='ticket_component',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
