# Generated by Django 2.2.10 on 2021-01-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180911_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('service', 'service'), ('development', 'development')], max_length=255, null=True, verbose_name='billing type'),
        ),
        migrations.AlterField(
            model_name='test',
            name='fixed_in_version',
            field=models.CharField(blank=True, choices=[('last_python2', 'last_python2')], max_length=255, verbose_name='fixed in version'),
        ),
        migrations.AlterField(
            model_name='test',
            name='version',
            field=models.CharField(choices=[('last_python2', 'last_python2')], max_length=255, verbose_name='version'),
        ),
    ]
