# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 12:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('columns', models.TextField()),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('hourly_rate', models.FloatField(null=True)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ticket_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField(default=0)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket state',
                'verbose_name_plural': 'ticket states',
            },
        ),
        migrations.CreateModel(
            name='ticket_flow_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='yats.ticket_flow')),
                ('now', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now', to='yats.ticket_flow')),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ticket_priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default=b'transparent', max_length=255)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket priority',
                'verbose_name_plural': 'ticket priorities',
            },
        ),
        migrations.CreateModel(
            name='ticket_resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket resolution',
                'verbose_name_plural': 'ticket resolutions',
            },
        ),
        migrations.CreateModel(
            name='ticket_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket type',
                'verbose_name_plural': 'ticket types',
            },
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('caption', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('close_date', models.DateTimeField(null=True)),
                ('last_action_date', models.DateTimeField(null=True)),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yats.organisation')),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.ticket_priority')),
                ('resolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.ticket_resolution')),
                ('state', models.ForeignKey(blank=True, default=yats.models.get_flow_start, null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.ticket_flow')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.ticket_type')),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tickets_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('comment', models.TextField()),
                ('action', models.SmallIntegerField(default=0)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yats.tickets')),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tickets_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('public', models.BooleanField(default=False)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yats.tickets')),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tickets_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('old', models.TextField()),
                ('new', models.TextField()),
                ('action', models.SmallIntegerField(default=0)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yats.tickets')),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tickets_participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yats.tickets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tickets_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('search', models.TextField()),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.organisation')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
