# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0002_auto_20180717_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='keep_it_simple',
            field=models.BooleanField(default=True),
        ),
    ]
