# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0003_tickets_keep_it_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets_participants',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
