# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0004_tickets_participants_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jabber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
