# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    tickets = apps.get_model('yats', 'tickets')
    for tic in tickets.objects.all():
        tic.uuid = uuid.uuid4()
        tic.save()

class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0005_userprofile_jabber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(create_uuid),
    ]
