# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0008_auto_20180823_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_priority',
            name='caldav',
            field=models.CharField(choices=[(b'HIGH', 'high'), (b'MEDIUM', 'medium'), (b'LOW', 'low'), (b'', 'none')], default=b'', max_length=255),
        ),
    ]
