# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0010_auto_20180823_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_priority',
            name='caldav',
            field=models.SmallIntegerField(default=0),
        ),
    ]
