# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import yats.models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0013_auto_20180829_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='hasAttachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boards',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='ticket_flow',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='ticket_flow',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='ticket_flow_edges',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='ticket_flow_edges',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='ticket_priority',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='ticket_priority',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='ticket_resolution',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='ticket_resolution',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='assigned'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='caption',
            field=models.CharField(max_length=255, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='close_date',
            field=models.DateTimeField(null=True, verbose_name='close date'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yats.organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='last_action_date',
            field=models.DateTimeField(null=True, verbose_name='last action'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.ticket_priority', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.ticket_resolution', verbose_name='resolution'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='state',
            field=models.ForeignKey(blank=True, default=yats.models.get_flow_start, null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.ticket_flow', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yats.ticket_type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='tickets_comments',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='tickets_comments',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='tickets_files',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='tickets_files',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='tickets_history',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='tickets_history',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='tickets_reports',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='tickets_reports',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
