# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 12:43
from __future__ import unicode_literals

from django.db import migrations

def checkHasAtt(apps, schema_editor):
    tickets = apps.get_model('yats', 'tickets')
    files = apps.get_model('yats', 'tickets_files')
    for ticket in tickets.objects.all():
        if files.objects.filter(ticket=ticket.pk).count() > 0:
            ticket.hasAttachments = True
            ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0014_auto_20180911_1440'),
    ]

    operations = [
        migrations.RunPython(checkHasAtt),
    ]
