# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0015_auto_20180911_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='hasComments',
            field=models.BooleanField(default=False),
        ),
    ]
