# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-05 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yats', '0021_userprofile_day_since_closed_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='docs_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('u_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('public', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yats.docs')),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['c_date'],
            },
        ),
        migrations.CreateModel(
            name='docs_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('u_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('old', models.TextField()),
                ('new', models.TextField()),
                ('action', models.SmallIntegerField(default=0)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yats.docs')),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
