# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-04 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0022_docs_files_docs_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets_comments',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
