# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0023_tickets_comments_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets_comments',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
