# Generated by Django 2.2.10 on 2021-01-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0025_docs_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_priority',
            name='color',
            field=models.CharField(default='transparent', max_length=255),
        ),
    ]
