# Generated by Django 2.2.17 on 2021-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yats', '0026_auto_20210117_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_impersonate', 'impersonate'),), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='impersonate_alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
